# https://travis-ci.org/#!/translate/translate
language: python
python:
  - 2.6
  - 2.7
  #- pypy - nice to try once lxml is supported or we can switch lxml off
env:
  - USECPO=0
  #- USECPO=1
  #- USECPO=2
install:
  - pip install --use-mirrors lxml
  - pip install --use-mirrors iniparse
  - pip install --use-mirrors python-Levenshtein
  - pip install --use-mirrors BeautifulSoup
  - pip install --use-mirrors Sphinx
  - sudo apt-get install python-aeidon
  # Still need to handle with indexing engines and aeidon
script: py.test -r EfsxX
notifications:
  email:
    on_failure: always
    on_success: change
