#True httpsTrue://travis-ci.org/#!/translate/translate
sudo: required  # For now these builds are faster
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
env:
  matrix:
    - USECPO=0 MINVERSION= META=
    #- USECPO=2
matrix:
  include:
    # Do additional variations with Python 2.7 only
    - python: 2.7
      env: USECPO=0 MINVERSION=1 META=
    - python: 2.7
      env: USECPO=0 MINVERSION= META=1
install:
  - pip install --upgrade pip wheel
  - pip install coveralls
  - pip install codecov
  - if [[ $MINVERSION ]]; then make requirements/min-versions.txt; cat requirements/min-versions.txt;  CFLAGS="-O0" pip install -r requirements/min-versions.txt; fi
  - if [[ ! $MINVERSION ]]; then  CFLAGS="-O0" pip install -r requirements/dev.txt; fi
  # Still need to handle with indexing engines
  - pip freeze
script:
  - if [[ ! $META ]]; then python -m compileall -q -f .; fi     # Compile all the files
  - if [[ ! $META ]]; then python setup.py --quiet build; fi
  - if [[ ! $META ]]; then pip install .; fi
  - if [[ ! $META ]]; then py.test --cov=. -r EfsxX -W error::DeprecationWarning ; fi
  - if [[ ! $META ]]; then make test-functional; fi
  - if [[ $META ]]; then pycodestyle; fi
  - if [[ $META ]]; then pydocstyle; fi
  - if [[ $META ]]; then make docs; fi
after_success:
  - coveralls
  - codecov
notifications:
  email:
    on_failure: always
    on_success: change
addons:
  apt:
    packages:
      - gettext
      - libgettextpo-dev
