# https://travis-ci.org/#!/translate/translate
language: python
python:
  - 2.6
  - 2.7
  - pypy
env:
  matrix:
    - USECPO=0 MINVERSION=1
    - USECPO=0 MINVERSION=
    #- USECPO=1
    #- USECPO=2
matrix:
  allow_failures:
    - python: pypy
  exclude:
    - python: pypy
      env: USECPO=0 MINVERSION=1
    - python: 2.6
      env: USECPO=0 MINVERSION=1
before_install:
  - sudo apt-get install python-aeidon
install:
  - if [[ $MINVERSION ]]; then rm min-required.txt; make min-required.txt; pip install -r min-required.txt; pip install --upgrade pytest; fi
  - if [[ ! $MINVERSION ]]; then pip install -r requirements/dev.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install --upgrade --pre lxml; fi
  # Still need to handle with indexing engines
  - pip freeze
script:
  # Compile all the files
  - python -m compileall -q -f .
  - python setup.py --quiet build
  - py.test --boxed -r EfsxX
  - ./tools/pep8.sh travis
  # -W report warnings as errors when building docs
  - cd docs; make SPHINXOPTS=-W html
notifications:
  email:
    on_failure: always
    on_success: change
