auto: true
markdown: kramdown

name: Translate Toolkit
description: A collection of useful tools for localization, and a powerful API for programmers of localization tools.
latest_version: 2.1.0
author: Translate House

about_url: http://translatehouse.org/about.html
docs_url: http://docs.translatehouse.org/projects/translate-toolkit/
gh_url: https://github.com/translate/translate
contact_url: mailto:dev@translate.org.za
