environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # We need wheel installed to build wheels
  - "python.exe -m pip install wheel"
  - "python.exe -m pip install -r requirements\\dev.txt"
  - "python.exe -m pip freeze"

build_script:
  # Build the compiled extension
  - "python setup.py build"

test_script:
  - "python.exe -m pip install ."
  - "python.exe -m pytest -r EfsxX"

after_test:
  - "python.exe setup.py bdist_wheel bdist_wininst"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*
