name: Distribution

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  setup:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Cache pip
      uses: actions/cache@v2.1.2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-setup-${{ hashFiles('requirements/*.txt') }}
    - name: Set up Python 3.7
      uses: actions/setup-python@v2.1.3
      with:
        python-version: 3.7
    - name: Install apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgettextpo-dev
    - name: Update pip
      run: pip install --upgrade pip wheel
    - name: Install pip dependencies
      run: |
        pip install -r requirements/dev.txt
    - name: Build sdist
      run: make build
    - name: Twine check
      run: twine check dist/*
    - name: Install test
      run: |
        virtualenv test-ttk-release
        . ./test-ttk-release/bin/activate
        pip install dist/translate-toolkit-*.tar.gz
        moz2po --help
    - name: Run setup
      run: coverage run ./setup.py sdist
    - name: Coverage
      run: coverage xml
    - uses: codecov/codecov-action@v1
      with:
        name: setup
