name: Distribution

on:
  push:
    branches-ignore:
    - dependabot/**
    - deepsource**
    tags:
    - '*'
  pull_request:

permissions:
  contents: read

jobs:
  setup:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.13'
    - uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b # v6.6.0
      with:
        enable-cache: true
        cache-dependency-glob: ''
        cache-suffix: '3.13'
    - name: Install apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgettextpo-dev
    - name: Build pakcage
      run: uv build
    - name: Twine check
      run: uvx twine check dist/*
    - name: pydistcheck
      run: uvx pydistcheck --inspect dist/*
    - name: pyroma
      run: uvx pyroma dist/*.tar.gz
    - name: check-wheel-contents
      run: uvx check-wheel-contents dist/*.whl
    - name: check-manifest
      run: uvx check-manifest -v
    - name: Install test (source)
      run: |
        uv venv test-ttk-release-src
        . ./test-ttk-release-src/bin/activate
        uv pip install dist/translate_toolkit-*.tar.gz
        moz2po --help
        python ./test-ttk-release-src/lib/python*/site-packages/translate/lang/identify.py README.rst
    - name: Install test (wheel)
      run: |
        uv venv test-ttk-release-whl
        . ./test-ttk-release-whl/bin/activate
        uv pip install dist/translate_toolkit*.whl
        moz2po --help
        python ./test-ttk-release-whl/lib/python*/site-packages/translate/lang/identify.py README.rst
    - uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5.5.0
      with:
        name: setup
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        path: ./dist/*

  pypi-publish:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
    needs:
    - setup
    runs-on: ubuntu-24.04
    permissions:
      # this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        # unpacks default artifact into dist/
        # if `name: artifact` is omitted, the action will create extra parent dir
        name: artifact
        path: dist

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4

  github-publish:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
    needs:
    - setup
    runs-on: ubuntu-24.04
    permissions:
      # this permission is mandatory for creating a release
      contents: write
    steps:
    - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        # unpacks default artifact into dist/
        # if `name: artifact` is omitted, the action will create extra parent dir
        name: artifact
        path: dist
    - uses: ncipollo/release-action@1c89adf39833729d8f85a31ccbc451b078733c80 # v1.19.1
      with:
        artifacts: dist/*
